/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointegrador.clinicamedica.view;

/**
 *
 * @author Phabi
 */
public class TelaPrincipalFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalFuncionario
     */
    public TelaPrincipalFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuFuncionario = new javax.swing.JMenu();
        jMenuFuncionarioAlterar = new javax.swing.JMenu();
        jMenuFuncionarioCadastrar = new javax.swing.JMenu();
        jMenuFuncionarioDeletar = new javax.swing.JMenu();
        jMenuFuncionarioVerificar = new javax.swing.JMenu();
        jMenuMedico = new javax.swing.JMenu();
        jMenuMedicoAlterar = new javax.swing.JMenu();
        jMenuMedicoCadastrar = new javax.swing.JMenu();
        jMenuMedicoDeletar = new javax.swing.JMenu();
        jMenuMedicoVerificar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Médica");
        setResizable(false);

        jMenuFuncionario.setText("Funcionário");
        jMenuFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuFuncionarioAlterar.setText("Alterar");
        jMenuFuncionario.add(jMenuFuncionarioAlterar);

        jMenuFuncionarioCadastrar.setText("Cadastrar");
        jMenuFuncionario.add(jMenuFuncionarioCadastrar);

        jMenuFuncionarioDeletar.setText("Deletar");
        jMenuFuncionario.add(jMenuFuncionarioDeletar);

        jMenuFuncionarioVerificar.setText("Verificar");
        jMenuFuncionario.add(jMenuFuncionarioVerificar);

        jMenuBarPrincipal.add(jMenuFuncionario);

        jMenuMedico.setText("Médico");
        jMenuMedico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuMedicoAlterar.setText("Alterar");
        jMenuMedico.add(jMenuMedicoAlterar);

        jMenuMedicoCadastrar.setText("Cadastrar");
        jMenuMedico.add(jMenuMedicoCadastrar);

        jMenuMedicoDeletar.setText("Deletar");
        jMenuMedico.add(jMenuMedicoDeletar);

        jMenuMedicoVerificar.setText("Verificar");
        jMenuMedico.add(jMenuMedicoVerificar);

        jMenuBarPrincipal.add(jMenuMedico);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuFuncionario;
    private javax.swing.JMenu jMenuFuncionarioAlterar;
    private javax.swing.JMenu jMenuFuncionarioCadastrar;
    private javax.swing.JMenu jMenuFuncionarioDeletar;
    private javax.swing.JMenu jMenuFuncionarioVerificar;
    private javax.swing.JMenu jMenuMedico;
    private javax.swing.JMenu jMenuMedicoAlterar;
    private javax.swing.JMenu jMenuMedicoCadastrar;
    private javax.swing.JMenu jMenuMedicoDeletar;
    private javax.swing.JMenu jMenuMedicoVerificar;
    // End of variables declaration//GEN-END:variables
}
